# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "descuentify"
client_id = "25292774762c4420b4e53e2b42c95e5e"
application_url = "https://descuentify-app.vercel.app"
embedded = true

[access_scopes]
scopes = "write_products,read_products,write_discounts,read_discounts,read_orders"

[auth]
redirect_urls = [
  "https://descuentify-app.vercel.app/auth/callback",
  "https://descuentify-app.vercel.app/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

[pos]
embedded = false
